image: golang:1.17.2

stages:
  - test
  - build

test:
  stage: test
  script:
    - make test

coverage:
  stage: test
  script:
    - make coverage

integration:
  stage: test
  script:
    - make integration

build:
  stage: build
  script:
    - make
