image: golang:1.17.2

stages:
  - test
  - build

lint:
  stage: test
  script:
    - make lint

coverage:
  stage: test
  script:
    - go install github.com/boumenot/gocover-cobertura@latest
    - make coverage
    - gocover-cobertura < cover.out > cover.xml
  coverage: '/total:.*\d+.\d+%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cover.xml

integration:
  stage: test
  script:
    - make integration

build:
  stage: build
  needs: []
  script:
    - make
